//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_Guitar_Client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="C_GUITAR", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class C_GUITAR : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomguitarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Micro1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Micro2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Micro3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BoisMancheField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BoisToucheField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BoisCorpsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomVibratoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nomguitar {
            get {
                return this.NomguitarField;
            }
            set {
                if ((object.ReferenceEquals(this.NomguitarField, value) != true)) {
                    this.NomguitarField = value;
                    this.RaisePropertyChanged("Nomguitar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Micro1 {
            get {
                return this.Micro1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Micro1Field, value) != true)) {
                    this.Micro1Field = value;
                    this.RaisePropertyChanged("Micro1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Micro2 {
            get {
                return this.Micro2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Micro2Field, value) != true)) {
                    this.Micro2Field = value;
                    this.RaisePropertyChanged("Micro2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Micro3 {
            get {
                return this.Micro3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Micro3Field, value) != true)) {
                    this.Micro3Field = value;
                    this.RaisePropertyChanged("Micro3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string BoisManche {
            get {
                return this.BoisMancheField;
            }
            set {
                if ((object.ReferenceEquals(this.BoisMancheField, value) != true)) {
                    this.BoisMancheField = value;
                    this.RaisePropertyChanged("BoisManche");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string BoisTouche {
            get {
                return this.BoisToucheField;
            }
            set {
                if ((object.ReferenceEquals(this.BoisToucheField, value) != true)) {
                    this.BoisToucheField = value;
                    this.RaisePropertyChanged("BoisTouche");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string BoisCorps {
            get {
                return this.BoisCorpsField;
            }
            set {
                if ((object.ReferenceEquals(this.BoisCorpsField, value) != true)) {
                    this.BoisCorpsField = value;
                    this.RaisePropertyChanged("BoisCorps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string NomVibrato {
            get {
                return this.NomVibratoField;
            }
            set {
                if ((object.ReferenceEquals(this.NomVibratoField, value) != true)) {
                    this.NomVibratoField = value;
                    this.RaisePropertyChanged("NomVibrato");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="C_TYPEBOIS", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class C_TYPEBOIS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomTypeBoisField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NomTypeBois {
            get {
                return this.NomTypeBoisField;
            }
            set {
                if ((object.ReferenceEquals(this.NomTypeBoisField, value) != true)) {
                    this.NomTypeBoisField = value;
                    this.RaisePropertyChanged("NomTypeBois");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="C_MICRO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class C_MICRO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContructeurField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Contructeur {
            get {
                return this.ContructeurField;
            }
            set {
                if ((object.ReferenceEquals(this.ContructeurField, value) != true)) {
                    this.ContructeurField = value;
                    this.RaisePropertyChanged("Contructeur");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="C_VIBRATO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class C_VIBRATO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomVibratoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NomVibrato {
            get {
                return this.NomVibratoField;
            }
            set {
                if ((object.ReferenceEquals(this.NomVibratoField, value) != true)) {
                    this.NomVibratoField = value;
                    this.RaisePropertyChanged("NomVibrato");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="C_COMMANDE", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class C_COMMANDE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idCommandeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateCommandeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MontantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelephoneClientField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string idCommande {
            get {
                return this.idCommandeField;
            }
            set {
                if ((object.ReferenceEquals(this.idCommandeField, value) != true)) {
                    this.idCommandeField = value;
                    this.RaisePropertyChanged("idCommande");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string NomClient {
            get {
                return this.NomClientField;
            }
            set {
                if ((object.ReferenceEquals(this.NomClientField, value) != true)) {
                    this.NomClientField = value;
                    this.RaisePropertyChanged("NomClient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DateCommande {
            get {
                return this.DateCommandeField;
            }
            set {
                if ((object.ReferenceEquals(this.DateCommandeField, value) != true)) {
                    this.DateCommandeField = value;
                    this.RaisePropertyChanged("DateCommande");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Montant {
            get {
                return this.MontantField;
            }
            set {
                if ((object.ReferenceEquals(this.MontantField, value) != true)) {
                    this.MontantField = value;
                    this.RaisePropertyChanged("Montant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string TelephoneClient {
            get {
                return this.TelephoneClientField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneClientField, value) != true)) {
                    this.TelephoneClientField = value;
                    this.RaisePropertyChanged("TelephoneClient");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WS_GUITARSoap")]
    public interface WS_GUITARSoap {
        
        // CODEGEN: Generating message contract since element name Nomguitar from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CommandeGuitar", ReplyAction="*")]
        TP_Guitar_Client.ServiceReference1.CommandeGuitarResponse CommandeGuitar(TP_Guitar_Client.ServiceReference1.CommandeGuitarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CommandeGuitar", ReplyAction="*")]
        System.Threading.Tasks.Task<TP_Guitar_Client.ServiceReference1.CommandeGuitarResponse> CommandeGuitarAsync(TP_Guitar_Client.ServiceReference1.CommandeGuitarRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllGuitarsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllGuitars", ReplyAction="*")]
        TP_Guitar_Client.ServiceReference1.GetAllGuitarsResponse GetAllGuitars(TP_Guitar_Client.ServiceReference1.GetAllGuitarsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllGuitars", ReplyAction="*")]
        System.Threading.Tasks.Task<TP_Guitar_Client.ServiceReference1.GetAllGuitarsResponse> GetAllGuitarsAsync(TP_Guitar_Client.ServiceReference1.GetAllGuitarsRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllTypeBoisResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllTypeBois", ReplyAction="*")]
        TP_Guitar_Client.ServiceReference1.GetAllTypeBoisResponse GetAllTypeBois(TP_Guitar_Client.ServiceReference1.GetAllTypeBoisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllTypeBois", ReplyAction="*")]
        System.Threading.Tasks.Task<TP_Guitar_Client.ServiceReference1.GetAllTypeBoisResponse> GetAllTypeBoisAsync(TP_Guitar_Client.ServiceReference1.GetAllTypeBoisRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllTypesMicroResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllTypesMicro", ReplyAction="*")]
        TP_Guitar_Client.ServiceReference1.GetAllTypesMicroResponse GetAllTypesMicro(TP_Guitar_Client.ServiceReference1.GetAllTypesMicroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllTypesMicro", ReplyAction="*")]
        System.Threading.Tasks.Task<TP_Guitar_Client.ServiceReference1.GetAllTypesMicroResponse> GetAllTypesMicroAsync(TP_Guitar_Client.ServiceReference1.GetAllTypesMicroRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllTypesVibratoResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllTypesVibrato", ReplyAction="*")]
        TP_Guitar_Client.ServiceReference1.GetAllTypesVibratoResponse GetAllTypesVibrato(TP_Guitar_Client.ServiceReference1.GetAllTypesVibratoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllTypesVibrato", ReplyAction="*")]
        System.Threading.Tasks.Task<TP_Guitar_Client.ServiceReference1.GetAllTypesVibratoResponse> GetAllTypesVibratoAsync(TP_Guitar_Client.ServiceReference1.GetAllTypesVibratoRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllCommandesExistantResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCommandesExistant", ReplyAction="*")]
        TP_Guitar_Client.ServiceReference1.GetAllCommandesExistantResponse GetAllCommandesExistant(TP_Guitar_Client.ServiceReference1.GetAllCommandesExistantRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCommandesExistant", ReplyAction="*")]
        System.Threading.Tasks.Task<TP_Guitar_Client.ServiceReference1.GetAllCommandesExistantResponse> GetAllCommandesExistantAsync(TP_Guitar_Client.ServiceReference1.GetAllCommandesExistantRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CommandeGuitarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CommandeGuitar", Namespace="http://tempuri.org/", Order=0)]
        public TP_Guitar_Client.ServiceReference1.CommandeGuitarRequestBody Body;
        
        public CommandeGuitarRequest() {
        }
        
        public CommandeGuitarRequest(TP_Guitar_Client.ServiceReference1.CommandeGuitarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CommandeGuitarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Nomguitar;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Micro1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Micro2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Micro3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string BoisManche;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string BoisTouche;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string BoisCorps;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string NomVibrato;
        
        public CommandeGuitarRequestBody() {
        }
        
        public CommandeGuitarRequestBody(string Nomguitar, string Micro1, string Micro2, string Micro3, string BoisManche, string BoisTouche, string BoisCorps, string NomVibrato) {
            this.Nomguitar = Nomguitar;
            this.Micro1 = Micro1;
            this.Micro2 = Micro2;
            this.Micro3 = Micro3;
            this.BoisManche = BoisManche;
            this.BoisTouche = BoisTouche;
            this.BoisCorps = BoisCorps;
            this.NomVibrato = NomVibrato;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CommandeGuitarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CommandeGuitarResponse", Namespace="http://tempuri.org/", Order=0)]
        public TP_Guitar_Client.ServiceReference1.CommandeGuitarResponseBody Body;
        
        public CommandeGuitarResponse() {
        }
        
        public CommandeGuitarResponse(TP_Guitar_Client.ServiceReference1.CommandeGuitarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CommandeGuitarResponseBody {
        
        public CommandeGuitarResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllGuitarsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllGuitars", Namespace="http://tempuri.org/", Order=0)]
        public TP_Guitar_Client.ServiceReference1.GetAllGuitarsRequestBody Body;
        
        public GetAllGuitarsRequest() {
        }
        
        public GetAllGuitarsRequest(TP_Guitar_Client.ServiceReference1.GetAllGuitarsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllGuitarsRequestBody {
        
        public GetAllGuitarsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllGuitarsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllGuitarsResponse", Namespace="http://tempuri.org/", Order=0)]
        public TP_Guitar_Client.ServiceReference1.GetAllGuitarsResponseBody Body;
        
        public GetAllGuitarsResponse() {
        }
        
        public GetAllGuitarsResponse(TP_Guitar_Client.ServiceReference1.GetAllGuitarsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllGuitarsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TP_Guitar_Client.ServiceReference1.C_GUITAR[] GetAllGuitarsResult;
        
        public GetAllGuitarsResponseBody() {
        }
        
        public GetAllGuitarsResponseBody(TP_Guitar_Client.ServiceReference1.C_GUITAR[] GetAllGuitarsResult) {
            this.GetAllGuitarsResult = GetAllGuitarsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTypeBoisRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllTypeBois", Namespace="http://tempuri.org/", Order=0)]
        public TP_Guitar_Client.ServiceReference1.GetAllTypeBoisRequestBody Body;
        
        public GetAllTypeBoisRequest() {
        }
        
        public GetAllTypeBoisRequest(TP_Guitar_Client.ServiceReference1.GetAllTypeBoisRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllTypeBoisRequestBody {
        
        public GetAllTypeBoisRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTypeBoisResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllTypeBoisResponse", Namespace="http://tempuri.org/", Order=0)]
        public TP_Guitar_Client.ServiceReference1.GetAllTypeBoisResponseBody Body;
        
        public GetAllTypeBoisResponse() {
        }
        
        public GetAllTypeBoisResponse(TP_Guitar_Client.ServiceReference1.GetAllTypeBoisResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllTypeBoisResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TP_Guitar_Client.ServiceReference1.C_TYPEBOIS[] GetAllTypeBoisResult;
        
        public GetAllTypeBoisResponseBody() {
        }
        
        public GetAllTypeBoisResponseBody(TP_Guitar_Client.ServiceReference1.C_TYPEBOIS[] GetAllTypeBoisResult) {
            this.GetAllTypeBoisResult = GetAllTypeBoisResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTypesMicroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllTypesMicro", Namespace="http://tempuri.org/", Order=0)]
        public TP_Guitar_Client.ServiceReference1.GetAllTypesMicroRequestBody Body;
        
        public GetAllTypesMicroRequest() {
        }
        
        public GetAllTypesMicroRequest(TP_Guitar_Client.ServiceReference1.GetAllTypesMicroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllTypesMicroRequestBody {
        
        public GetAllTypesMicroRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTypesMicroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllTypesMicroResponse", Namespace="http://tempuri.org/", Order=0)]
        public TP_Guitar_Client.ServiceReference1.GetAllTypesMicroResponseBody Body;
        
        public GetAllTypesMicroResponse() {
        }
        
        public GetAllTypesMicroResponse(TP_Guitar_Client.ServiceReference1.GetAllTypesMicroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllTypesMicroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TP_Guitar_Client.ServiceReference1.C_MICRO[] GetAllTypesMicroResult;
        
        public GetAllTypesMicroResponseBody() {
        }
        
        public GetAllTypesMicroResponseBody(TP_Guitar_Client.ServiceReference1.C_MICRO[] GetAllTypesMicroResult) {
            this.GetAllTypesMicroResult = GetAllTypesMicroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTypesVibratoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllTypesVibrato", Namespace="http://tempuri.org/", Order=0)]
        public TP_Guitar_Client.ServiceReference1.GetAllTypesVibratoRequestBody Body;
        
        public GetAllTypesVibratoRequest() {
        }
        
        public GetAllTypesVibratoRequest(TP_Guitar_Client.ServiceReference1.GetAllTypesVibratoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllTypesVibratoRequestBody {
        
        public GetAllTypesVibratoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTypesVibratoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllTypesVibratoResponse", Namespace="http://tempuri.org/", Order=0)]
        public TP_Guitar_Client.ServiceReference1.GetAllTypesVibratoResponseBody Body;
        
        public GetAllTypesVibratoResponse() {
        }
        
        public GetAllTypesVibratoResponse(TP_Guitar_Client.ServiceReference1.GetAllTypesVibratoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllTypesVibratoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TP_Guitar_Client.ServiceReference1.C_VIBRATO[] GetAllTypesVibratoResult;
        
        public GetAllTypesVibratoResponseBody() {
        }
        
        public GetAllTypesVibratoResponseBody(TP_Guitar_Client.ServiceReference1.C_VIBRATO[] GetAllTypesVibratoResult) {
            this.GetAllTypesVibratoResult = GetAllTypesVibratoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCommandesExistantRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCommandesExistant", Namespace="http://tempuri.org/", Order=0)]
        public TP_Guitar_Client.ServiceReference1.GetAllCommandesExistantRequestBody Body;
        
        public GetAllCommandesExistantRequest() {
        }
        
        public GetAllCommandesExistantRequest(TP_Guitar_Client.ServiceReference1.GetAllCommandesExistantRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllCommandesExistantRequestBody {
        
        public GetAllCommandesExistantRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCommandesExistantResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCommandesExistantResponse", Namespace="http://tempuri.org/", Order=0)]
        public TP_Guitar_Client.ServiceReference1.GetAllCommandesExistantResponseBody Body;
        
        public GetAllCommandesExistantResponse() {
        }
        
        public GetAllCommandesExistantResponse(TP_Guitar_Client.ServiceReference1.GetAllCommandesExistantResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllCommandesExistantResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TP_Guitar_Client.ServiceReference1.C_COMMANDE[] GetAllCommandesExistantResult;
        
        public GetAllCommandesExistantResponseBody() {
        }
        
        public GetAllCommandesExistantResponseBody(TP_Guitar_Client.ServiceReference1.C_COMMANDE[] GetAllCommandesExistantResult) {
            this.GetAllCommandesExistantResult = GetAllCommandesExistantResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_GUITARSoapChannel : TP_Guitar_Client.ServiceReference1.WS_GUITARSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_GUITARSoapClient : System.ServiceModel.ClientBase<TP_Guitar_Client.ServiceReference1.WS_GUITARSoap>, TP_Guitar_Client.ServiceReference1.WS_GUITARSoap {
        
        public WS_GUITARSoapClient() {
        }
        
        public WS_GUITARSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_GUITARSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_GUITARSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_GUITARSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TP_Guitar_Client.ServiceReference1.CommandeGuitarResponse TP_Guitar_Client.ServiceReference1.WS_GUITARSoap.CommandeGuitar(TP_Guitar_Client.ServiceReference1.CommandeGuitarRequest request) {
            return base.Channel.CommandeGuitar(request);
        }
        
        public void CommandeGuitar(string Nomguitar, string Micro1, string Micro2, string Micro3, string BoisManche, string BoisTouche, string BoisCorps, string NomVibrato) {
            TP_Guitar_Client.ServiceReference1.CommandeGuitarRequest inValue = new TP_Guitar_Client.ServiceReference1.CommandeGuitarRequest();
            inValue.Body = new TP_Guitar_Client.ServiceReference1.CommandeGuitarRequestBody();
            inValue.Body.Nomguitar = Nomguitar;
            inValue.Body.Micro1 = Micro1;
            inValue.Body.Micro2 = Micro2;
            inValue.Body.Micro3 = Micro3;
            inValue.Body.BoisManche = BoisManche;
            inValue.Body.BoisTouche = BoisTouche;
            inValue.Body.BoisCorps = BoisCorps;
            inValue.Body.NomVibrato = NomVibrato;
            TP_Guitar_Client.ServiceReference1.CommandeGuitarResponse retVal = ((TP_Guitar_Client.ServiceReference1.WS_GUITARSoap)(this)).CommandeGuitar(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TP_Guitar_Client.ServiceReference1.CommandeGuitarResponse> TP_Guitar_Client.ServiceReference1.WS_GUITARSoap.CommandeGuitarAsync(TP_Guitar_Client.ServiceReference1.CommandeGuitarRequest request) {
            return base.Channel.CommandeGuitarAsync(request);
        }
        
        public System.Threading.Tasks.Task<TP_Guitar_Client.ServiceReference1.CommandeGuitarResponse> CommandeGuitarAsync(string Nomguitar, string Micro1, string Micro2, string Micro3, string BoisManche, string BoisTouche, string BoisCorps, string NomVibrato) {
            TP_Guitar_Client.ServiceReference1.CommandeGuitarRequest inValue = new TP_Guitar_Client.ServiceReference1.CommandeGuitarRequest();
            inValue.Body = new TP_Guitar_Client.ServiceReference1.CommandeGuitarRequestBody();
            inValue.Body.Nomguitar = Nomguitar;
            inValue.Body.Micro1 = Micro1;
            inValue.Body.Micro2 = Micro2;
            inValue.Body.Micro3 = Micro3;
            inValue.Body.BoisManche = BoisManche;
            inValue.Body.BoisTouche = BoisTouche;
            inValue.Body.BoisCorps = BoisCorps;
            inValue.Body.NomVibrato = NomVibrato;
            return ((TP_Guitar_Client.ServiceReference1.WS_GUITARSoap)(this)).CommandeGuitarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TP_Guitar_Client.ServiceReference1.GetAllGuitarsResponse TP_Guitar_Client.ServiceReference1.WS_GUITARSoap.GetAllGuitars(TP_Guitar_Client.ServiceReference1.GetAllGuitarsRequest request) {
            return base.Channel.GetAllGuitars(request);
        }
        
        public TP_Guitar_Client.ServiceReference1.C_GUITAR[] GetAllGuitars() {
            TP_Guitar_Client.ServiceReference1.GetAllGuitarsRequest inValue = new TP_Guitar_Client.ServiceReference1.GetAllGuitarsRequest();
            inValue.Body = new TP_Guitar_Client.ServiceReference1.GetAllGuitarsRequestBody();
            TP_Guitar_Client.ServiceReference1.GetAllGuitarsResponse retVal = ((TP_Guitar_Client.ServiceReference1.WS_GUITARSoap)(this)).GetAllGuitars(inValue);
            return retVal.Body.GetAllGuitarsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TP_Guitar_Client.ServiceReference1.GetAllGuitarsResponse> TP_Guitar_Client.ServiceReference1.WS_GUITARSoap.GetAllGuitarsAsync(TP_Guitar_Client.ServiceReference1.GetAllGuitarsRequest request) {
            return base.Channel.GetAllGuitarsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TP_Guitar_Client.ServiceReference1.GetAllGuitarsResponse> GetAllGuitarsAsync() {
            TP_Guitar_Client.ServiceReference1.GetAllGuitarsRequest inValue = new TP_Guitar_Client.ServiceReference1.GetAllGuitarsRequest();
            inValue.Body = new TP_Guitar_Client.ServiceReference1.GetAllGuitarsRequestBody();
            return ((TP_Guitar_Client.ServiceReference1.WS_GUITARSoap)(this)).GetAllGuitarsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TP_Guitar_Client.ServiceReference1.GetAllTypeBoisResponse TP_Guitar_Client.ServiceReference1.WS_GUITARSoap.GetAllTypeBois(TP_Guitar_Client.ServiceReference1.GetAllTypeBoisRequest request) {
            return base.Channel.GetAllTypeBois(request);
        }
        
        public TP_Guitar_Client.ServiceReference1.C_TYPEBOIS[] GetAllTypeBois() {
            TP_Guitar_Client.ServiceReference1.GetAllTypeBoisRequest inValue = new TP_Guitar_Client.ServiceReference1.GetAllTypeBoisRequest();
            inValue.Body = new TP_Guitar_Client.ServiceReference1.GetAllTypeBoisRequestBody();
            TP_Guitar_Client.ServiceReference1.GetAllTypeBoisResponse retVal = ((TP_Guitar_Client.ServiceReference1.WS_GUITARSoap)(this)).GetAllTypeBois(inValue);
            return retVal.Body.GetAllTypeBoisResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TP_Guitar_Client.ServiceReference1.GetAllTypeBoisResponse> TP_Guitar_Client.ServiceReference1.WS_GUITARSoap.GetAllTypeBoisAsync(TP_Guitar_Client.ServiceReference1.GetAllTypeBoisRequest request) {
            return base.Channel.GetAllTypeBoisAsync(request);
        }
        
        public System.Threading.Tasks.Task<TP_Guitar_Client.ServiceReference1.GetAllTypeBoisResponse> GetAllTypeBoisAsync() {
            TP_Guitar_Client.ServiceReference1.GetAllTypeBoisRequest inValue = new TP_Guitar_Client.ServiceReference1.GetAllTypeBoisRequest();
            inValue.Body = new TP_Guitar_Client.ServiceReference1.GetAllTypeBoisRequestBody();
            return ((TP_Guitar_Client.ServiceReference1.WS_GUITARSoap)(this)).GetAllTypeBoisAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TP_Guitar_Client.ServiceReference1.GetAllTypesMicroResponse TP_Guitar_Client.ServiceReference1.WS_GUITARSoap.GetAllTypesMicro(TP_Guitar_Client.ServiceReference1.GetAllTypesMicroRequest request) {
            return base.Channel.GetAllTypesMicro(request);
        }
        
        public TP_Guitar_Client.ServiceReference1.C_MICRO[] GetAllTypesMicro() {
            TP_Guitar_Client.ServiceReference1.GetAllTypesMicroRequest inValue = new TP_Guitar_Client.ServiceReference1.GetAllTypesMicroRequest();
            inValue.Body = new TP_Guitar_Client.ServiceReference1.GetAllTypesMicroRequestBody();
            TP_Guitar_Client.ServiceReference1.GetAllTypesMicroResponse retVal = ((TP_Guitar_Client.ServiceReference1.WS_GUITARSoap)(this)).GetAllTypesMicro(inValue);
            return retVal.Body.GetAllTypesMicroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TP_Guitar_Client.ServiceReference1.GetAllTypesMicroResponse> TP_Guitar_Client.ServiceReference1.WS_GUITARSoap.GetAllTypesMicroAsync(TP_Guitar_Client.ServiceReference1.GetAllTypesMicroRequest request) {
            return base.Channel.GetAllTypesMicroAsync(request);
        }
        
        public System.Threading.Tasks.Task<TP_Guitar_Client.ServiceReference1.GetAllTypesMicroResponse> GetAllTypesMicroAsync() {
            TP_Guitar_Client.ServiceReference1.GetAllTypesMicroRequest inValue = new TP_Guitar_Client.ServiceReference1.GetAllTypesMicroRequest();
            inValue.Body = new TP_Guitar_Client.ServiceReference1.GetAllTypesMicroRequestBody();
            return ((TP_Guitar_Client.ServiceReference1.WS_GUITARSoap)(this)).GetAllTypesMicroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TP_Guitar_Client.ServiceReference1.GetAllTypesVibratoResponse TP_Guitar_Client.ServiceReference1.WS_GUITARSoap.GetAllTypesVibrato(TP_Guitar_Client.ServiceReference1.GetAllTypesVibratoRequest request) {
            return base.Channel.GetAllTypesVibrato(request);
        }
        
        public TP_Guitar_Client.ServiceReference1.C_VIBRATO[] GetAllTypesVibrato() {
            TP_Guitar_Client.ServiceReference1.GetAllTypesVibratoRequest inValue = new TP_Guitar_Client.ServiceReference1.GetAllTypesVibratoRequest();
            inValue.Body = new TP_Guitar_Client.ServiceReference1.GetAllTypesVibratoRequestBody();
            TP_Guitar_Client.ServiceReference1.GetAllTypesVibratoResponse retVal = ((TP_Guitar_Client.ServiceReference1.WS_GUITARSoap)(this)).GetAllTypesVibrato(inValue);
            return retVal.Body.GetAllTypesVibratoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TP_Guitar_Client.ServiceReference1.GetAllTypesVibratoResponse> TP_Guitar_Client.ServiceReference1.WS_GUITARSoap.GetAllTypesVibratoAsync(TP_Guitar_Client.ServiceReference1.GetAllTypesVibratoRequest request) {
            return base.Channel.GetAllTypesVibratoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TP_Guitar_Client.ServiceReference1.GetAllTypesVibratoResponse> GetAllTypesVibratoAsync() {
            TP_Guitar_Client.ServiceReference1.GetAllTypesVibratoRequest inValue = new TP_Guitar_Client.ServiceReference1.GetAllTypesVibratoRequest();
            inValue.Body = new TP_Guitar_Client.ServiceReference1.GetAllTypesVibratoRequestBody();
            return ((TP_Guitar_Client.ServiceReference1.WS_GUITARSoap)(this)).GetAllTypesVibratoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TP_Guitar_Client.ServiceReference1.GetAllCommandesExistantResponse TP_Guitar_Client.ServiceReference1.WS_GUITARSoap.GetAllCommandesExistant(TP_Guitar_Client.ServiceReference1.GetAllCommandesExistantRequest request) {
            return base.Channel.GetAllCommandesExistant(request);
        }
        
        public TP_Guitar_Client.ServiceReference1.C_COMMANDE[] GetAllCommandesExistant() {
            TP_Guitar_Client.ServiceReference1.GetAllCommandesExistantRequest inValue = new TP_Guitar_Client.ServiceReference1.GetAllCommandesExistantRequest();
            inValue.Body = new TP_Guitar_Client.ServiceReference1.GetAllCommandesExistantRequestBody();
            TP_Guitar_Client.ServiceReference1.GetAllCommandesExistantResponse retVal = ((TP_Guitar_Client.ServiceReference1.WS_GUITARSoap)(this)).GetAllCommandesExistant(inValue);
            return retVal.Body.GetAllCommandesExistantResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TP_Guitar_Client.ServiceReference1.GetAllCommandesExistantResponse> TP_Guitar_Client.ServiceReference1.WS_GUITARSoap.GetAllCommandesExistantAsync(TP_Guitar_Client.ServiceReference1.GetAllCommandesExistantRequest request) {
            return base.Channel.GetAllCommandesExistantAsync(request);
        }
        
        public System.Threading.Tasks.Task<TP_Guitar_Client.ServiceReference1.GetAllCommandesExistantResponse> GetAllCommandesExistantAsync() {
            TP_Guitar_Client.ServiceReference1.GetAllCommandesExistantRequest inValue = new TP_Guitar_Client.ServiceReference1.GetAllCommandesExistantRequest();
            inValue.Body = new TP_Guitar_Client.ServiceReference1.GetAllCommandesExistantRequestBody();
            return ((TP_Guitar_Client.ServiceReference1.WS_GUITARSoap)(this)).GetAllCommandesExistantAsync(inValue);
        }
    }
}
