//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_Guitar_Client.WS_GUITAR_Client {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="C_GUITAR", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class C_GUITAR : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomguitarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Micro1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Micro2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Micro3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BoisMancheField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BoisToucheField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BoisCorpsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomVibratoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nomguitar {
            get {
                return this.NomguitarField;
            }
            set {
                if ((object.ReferenceEquals(this.NomguitarField, value) != true)) {
                    this.NomguitarField = value;
                    this.RaisePropertyChanged("Nomguitar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Micro1 {
            get {
                return this.Micro1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Micro1Field, value) != true)) {
                    this.Micro1Field = value;
                    this.RaisePropertyChanged("Micro1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Micro2 {
            get {
                return this.Micro2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Micro2Field, value) != true)) {
                    this.Micro2Field = value;
                    this.RaisePropertyChanged("Micro2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Micro3 {
            get {
                return this.Micro3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Micro3Field, value) != true)) {
                    this.Micro3Field = value;
                    this.RaisePropertyChanged("Micro3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string BoisManche {
            get {
                return this.BoisMancheField;
            }
            set {
                if ((object.ReferenceEquals(this.BoisMancheField, value) != true)) {
                    this.BoisMancheField = value;
                    this.RaisePropertyChanged("BoisManche");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string BoisTouche {
            get {
                return this.BoisToucheField;
            }
            set {
                if ((object.ReferenceEquals(this.BoisToucheField, value) != true)) {
                    this.BoisToucheField = value;
                    this.RaisePropertyChanged("BoisTouche");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string BoisCorps {
            get {
                return this.BoisCorpsField;
            }
            set {
                if ((object.ReferenceEquals(this.BoisCorpsField, value) != true)) {
                    this.BoisCorpsField = value;
                    this.RaisePropertyChanged("BoisCorps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string NomVibrato {
            get {
                return this.NomVibratoField;
            }
            set {
                if ((object.ReferenceEquals(this.NomVibratoField, value) != true)) {
                    this.NomVibratoField = value;
                    this.RaisePropertyChanged("NomVibrato");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="C_TYPEBOIS", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class C_TYPEBOIS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomTypeBoisField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NomTypeBois {
            get {
                return this.NomTypeBoisField;
            }
            set {
                if ((object.ReferenceEquals(this.NomTypeBoisField, value) != true)) {
                    this.NomTypeBoisField = value;
                    this.RaisePropertyChanged("NomTypeBois");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="C_MICRO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class C_MICRO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContructeurField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Contructeur {
            get {
                return this.ContructeurField;
            }
            set {
                if ((object.ReferenceEquals(this.ContructeurField, value) != true)) {
                    this.ContructeurField = value;
                    this.RaisePropertyChanged("Contructeur");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="C_VIBRATO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class C_VIBRATO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomVibratoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NomVibrato {
            get {
                return this.NomVibratoField;
            }
            set {
                if ((object.ReferenceEquals(this.NomVibratoField, value) != true)) {
                    this.NomVibratoField = value;
                    this.RaisePropertyChanged("NomVibrato");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="C_COMMANDE", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class C_COMMANDE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idCommandeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateCommandeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MontantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelephoneClientField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string idCommande {
            get {
                return this.idCommandeField;
            }
            set {
                if ((object.ReferenceEquals(this.idCommandeField, value) != true)) {
                    this.idCommandeField = value;
                    this.RaisePropertyChanged("idCommande");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string NomClient {
            get {
                return this.NomClientField;
            }
            set {
                if ((object.ReferenceEquals(this.NomClientField, value) != true)) {
                    this.NomClientField = value;
                    this.RaisePropertyChanged("NomClient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DateCommande {
            get {
                return this.DateCommandeField;
            }
            set {
                if ((object.ReferenceEquals(this.DateCommandeField, value) != true)) {
                    this.DateCommandeField = value;
                    this.RaisePropertyChanged("DateCommande");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Montant {
            get {
                return this.MontantField;
            }
            set {
                if ((object.ReferenceEquals(this.MontantField, value) != true)) {
                    this.MontantField = value;
                    this.RaisePropertyChanged("Montant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string TelephoneClient {
            get {
                return this.TelephoneClientField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneClientField, value) != true)) {
                    this.TelephoneClientField = value;
                    this.RaisePropertyChanged("TelephoneClient");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="C_BON_COMMANDE", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class C_BON_COMMANDE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int NroCommandeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelephoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomguitarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string M_Pos_1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string M_Pos_2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string M_Pos_3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Bois_CorpsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Bois_ToucheField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Bois_MancheField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateCommandeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MontantField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int NroCommande {
            get {
                return this.NroCommandeField;
            }
            set {
                if ((this.NroCommandeField.Equals(value) != true)) {
                    this.NroCommandeField = value;
                    this.RaisePropertyChanged("NroCommande");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Client {
            get {
                return this.ClientField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientField, value) != true)) {
                    this.ClientField = value;
                    this.RaisePropertyChanged("Client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Telephone {
            get {
                return this.TelephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneField, value) != true)) {
                    this.TelephoneField = value;
                    this.RaisePropertyChanged("Telephone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Nomguitar {
            get {
                return this.NomguitarField;
            }
            set {
                if ((object.ReferenceEquals(this.NomguitarField, value) != true)) {
                    this.NomguitarField = value;
                    this.RaisePropertyChanged("Nomguitar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string M_Pos_1 {
            get {
                return this.M_Pos_1Field;
            }
            set {
                if ((object.ReferenceEquals(this.M_Pos_1Field, value) != true)) {
                    this.M_Pos_1Field = value;
                    this.RaisePropertyChanged("M_Pos_1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string M_Pos_2 {
            get {
                return this.M_Pos_2Field;
            }
            set {
                if ((object.ReferenceEquals(this.M_Pos_2Field, value) != true)) {
                    this.M_Pos_2Field = value;
                    this.RaisePropertyChanged("M_Pos_2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string M_Pos_3 {
            get {
                return this.M_Pos_3Field;
            }
            set {
                if ((object.ReferenceEquals(this.M_Pos_3Field, value) != true)) {
                    this.M_Pos_3Field = value;
                    this.RaisePropertyChanged("M_Pos_3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Bois_Corps {
            get {
                return this.Bois_CorpsField;
            }
            set {
                if ((object.ReferenceEquals(this.Bois_CorpsField, value) != true)) {
                    this.Bois_CorpsField = value;
                    this.RaisePropertyChanged("Bois_Corps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Bois_Touche {
            get {
                return this.Bois_ToucheField;
            }
            set {
                if ((object.ReferenceEquals(this.Bois_ToucheField, value) != true)) {
                    this.Bois_ToucheField = value;
                    this.RaisePropertyChanged("Bois_Touche");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Bois_Manche {
            get {
                return this.Bois_MancheField;
            }
            set {
                if ((object.ReferenceEquals(this.Bois_MancheField, value) != true)) {
                    this.Bois_MancheField = value;
                    this.RaisePropertyChanged("Bois_Manche");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string DateCommande {
            get {
                return this.DateCommandeField;
            }
            set {
                if ((object.ReferenceEquals(this.DateCommandeField, value) != true)) {
                    this.DateCommandeField = value;
                    this.RaisePropertyChanged("DateCommande");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Montant {
            get {
                return this.MontantField;
            }
            set {
                if ((object.ReferenceEquals(this.MontantField, value) != true)) {
                    this.MontantField = value;
                    this.RaisePropertyChanged("Montant");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_GUITAR_Client.WS_GUITARSoap")]
    public interface WS_GUITARSoap {
        
        // CODEGEN: Generating message contract since element name NomClient from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NouvelleCommande", ReplyAction="*")]
        TP_Guitar_Client.WS_GUITAR_Client.NouvelleCommandeResponse NouvelleCommande(TP_Guitar_Client.WS_GUITAR_Client.NouvelleCommandeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NouvelleCommande", ReplyAction="*")]
        System.Threading.Tasks.Task<TP_Guitar_Client.WS_GUITAR_Client.NouvelleCommandeResponse> NouvelleCommandeAsync(TP_Guitar_Client.WS_GUITAR_Client.NouvelleCommandeRequest request);
        
        // CODEGEN: Generating message contract since element name Nomguitar from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CommandeGuitar", ReplyAction="*")]
        TP_Guitar_Client.WS_GUITAR_Client.CommandeGuitarResponse CommandeGuitar(TP_Guitar_Client.WS_GUITAR_Client.CommandeGuitarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CommandeGuitar", ReplyAction="*")]
        System.Threading.Tasks.Task<TP_Guitar_Client.WS_GUITAR_Client.CommandeGuitarResponse> CommandeGuitarAsync(TP_Guitar_Client.WS_GUITAR_Client.CommandeGuitarRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllGuitarsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllGuitars", ReplyAction="*")]
        TP_Guitar_Client.WS_GUITAR_Client.GetAllGuitarsResponse GetAllGuitars(TP_Guitar_Client.WS_GUITAR_Client.GetAllGuitarsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllGuitars", ReplyAction="*")]
        System.Threading.Tasks.Task<TP_Guitar_Client.WS_GUITAR_Client.GetAllGuitarsResponse> GetAllGuitarsAsync(TP_Guitar_Client.WS_GUITAR_Client.GetAllGuitarsRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllTypeBoisResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllTypeBois", ReplyAction="*")]
        TP_Guitar_Client.WS_GUITAR_Client.GetAllTypeBoisResponse GetAllTypeBois(TP_Guitar_Client.WS_GUITAR_Client.GetAllTypeBoisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllTypeBois", ReplyAction="*")]
        System.Threading.Tasks.Task<TP_Guitar_Client.WS_GUITAR_Client.GetAllTypeBoisResponse> GetAllTypeBoisAsync(TP_Guitar_Client.WS_GUITAR_Client.GetAllTypeBoisRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllTypesMicroResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllTypesMicro", ReplyAction="*")]
        TP_Guitar_Client.WS_GUITAR_Client.GetAllTypesMicroResponse GetAllTypesMicro(TP_Guitar_Client.WS_GUITAR_Client.GetAllTypesMicroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllTypesMicro", ReplyAction="*")]
        System.Threading.Tasks.Task<TP_Guitar_Client.WS_GUITAR_Client.GetAllTypesMicroResponse> GetAllTypesMicroAsync(TP_Guitar_Client.WS_GUITAR_Client.GetAllTypesMicroRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllTypesVibratoResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllTypesVibrato", ReplyAction="*")]
        TP_Guitar_Client.WS_GUITAR_Client.GetAllTypesVibratoResponse GetAllTypesVibrato(TP_Guitar_Client.WS_GUITAR_Client.GetAllTypesVibratoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllTypesVibrato", ReplyAction="*")]
        System.Threading.Tasks.Task<TP_Guitar_Client.WS_GUITAR_Client.GetAllTypesVibratoResponse> GetAllTypesVibratoAsync(TP_Guitar_Client.WS_GUITAR_Client.GetAllTypesVibratoRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllCommandesExistantResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCommandesExistant", ReplyAction="*")]
        TP_Guitar_Client.WS_GUITAR_Client.GetAllCommandesExistantResponse GetAllCommandesExistant(TP_Guitar_Client.WS_GUITAR_Client.GetAllCommandesExistantRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCommandesExistant", ReplyAction="*")]
        System.Threading.Tasks.Task<TP_Guitar_Client.WS_GUITAR_Client.GetAllCommandesExistantResponse> GetAllCommandesExistantAsync(TP_Guitar_Client.WS_GUITAR_Client.GetAllCommandesExistantRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllCommandesFaitesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCommandesFaites", ReplyAction="*")]
        TP_Guitar_Client.WS_GUITAR_Client.GetAllCommandesFaitesResponse GetAllCommandesFaites(TP_Guitar_Client.WS_GUITAR_Client.GetAllCommandesFaitesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCommandesFaites", ReplyAction="*")]
        System.Threading.Tasks.Task<TP_Guitar_Client.WS_GUITAR_Client.GetAllCommandesFaitesResponse> GetAllCommandesFaitesAsync(TP_Guitar_Client.WS_GUITAR_Client.GetAllCommandesFaitesRequest request);
        
        // CODEGEN: Generating message contract since element name GetCommandeByIDResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCommandeByID", ReplyAction="*")]
        TP_Guitar_Client.WS_GUITAR_Client.GetCommandeByIDResponse GetCommandeByID(TP_Guitar_Client.WS_GUITAR_Client.GetCommandeByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCommandeByID", ReplyAction="*")]
        System.Threading.Tasks.Task<TP_Guitar_Client.WS_GUITAR_Client.GetCommandeByIDResponse> GetCommandeByIDAsync(TP_Guitar_Client.WS_GUITAR_Client.GetCommandeByIDRequest request);
        
        // CODEGEN: Generating message contract since element name GetLastCommandeIDResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLastCommandeID", ReplyAction="*")]
        TP_Guitar_Client.WS_GUITAR_Client.GetLastCommandeIDResponse GetLastCommandeID(TP_Guitar_Client.WS_GUITAR_Client.GetLastCommandeIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLastCommandeID", ReplyAction="*")]
        System.Threading.Tasks.Task<TP_Guitar_Client.WS_GUITAR_Client.GetLastCommandeIDResponse> GetLastCommandeIDAsync(TP_Guitar_Client.WS_GUITAR_Client.GetLastCommandeIDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NouvelleCommandeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NouvelleCommande", Namespace="http://tempuri.org/", Order=0)]
        public TP_Guitar_Client.WS_GUITAR_Client.NouvelleCommandeRequestBody Body;
        
        public NouvelleCommandeRequest() {
        }
        
        public NouvelleCommandeRequest(TP_Guitar_Client.WS_GUITAR_Client.NouvelleCommandeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NouvelleCommandeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NomClient;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DateCommande;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Montant;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TelephoneClient;
        
        public NouvelleCommandeRequestBody() {
        }
        
        public NouvelleCommandeRequestBody(string NomClient, string DateCommande, string Montant, string TelephoneClient) {
            this.NomClient = NomClient;
            this.DateCommande = DateCommande;
            this.Montant = Montant;
            this.TelephoneClient = TelephoneClient;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NouvelleCommandeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NouvelleCommandeResponse", Namespace="http://tempuri.org/", Order=0)]
        public TP_Guitar_Client.WS_GUITAR_Client.NouvelleCommandeResponseBody Body;
        
        public NouvelleCommandeResponse() {
        }
        
        public NouvelleCommandeResponse(TP_Guitar_Client.WS_GUITAR_Client.NouvelleCommandeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NouvelleCommandeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NouvelleCommandeResult;
        
        public NouvelleCommandeResponseBody() {
        }
        
        public NouvelleCommandeResponseBody(string NouvelleCommandeResult) {
            this.NouvelleCommandeResult = NouvelleCommandeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CommandeGuitarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CommandeGuitar", Namespace="http://tempuri.org/", Order=0)]
        public TP_Guitar_Client.WS_GUITAR_Client.CommandeGuitarRequestBody Body;
        
        public CommandeGuitarRequest() {
        }
        
        public CommandeGuitarRequest(TP_Guitar_Client.WS_GUITAR_Client.CommandeGuitarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CommandeGuitarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Nomguitar;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Micro1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Micro2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Micro3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string BoisManche;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string BoisTouche;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string BoisCorps;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string NomVibrato;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int idCommande;
        
        public CommandeGuitarRequestBody() {
        }
        
        public CommandeGuitarRequestBody(string Nomguitar, string Micro1, string Micro2, string Micro3, string BoisManche, string BoisTouche, string BoisCorps, string NomVibrato, int idCommande) {
            this.Nomguitar = Nomguitar;
            this.Micro1 = Micro1;
            this.Micro2 = Micro2;
            this.Micro3 = Micro3;
            this.BoisManche = BoisManche;
            this.BoisTouche = BoisTouche;
            this.BoisCorps = BoisCorps;
            this.NomVibrato = NomVibrato;
            this.idCommande = idCommande;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CommandeGuitarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CommandeGuitarResponse", Namespace="http://tempuri.org/", Order=0)]
        public TP_Guitar_Client.WS_GUITAR_Client.CommandeGuitarResponseBody Body;
        
        public CommandeGuitarResponse() {
        }
        
        public CommandeGuitarResponse(TP_Guitar_Client.WS_GUITAR_Client.CommandeGuitarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CommandeGuitarResponseBody {
        
        public CommandeGuitarResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllGuitarsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllGuitars", Namespace="http://tempuri.org/", Order=0)]
        public TP_Guitar_Client.WS_GUITAR_Client.GetAllGuitarsRequestBody Body;
        
        public GetAllGuitarsRequest() {
        }
        
        public GetAllGuitarsRequest(TP_Guitar_Client.WS_GUITAR_Client.GetAllGuitarsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllGuitarsRequestBody {
        
        public GetAllGuitarsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllGuitarsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllGuitarsResponse", Namespace="http://tempuri.org/", Order=0)]
        public TP_Guitar_Client.WS_GUITAR_Client.GetAllGuitarsResponseBody Body;
        
        public GetAllGuitarsResponse() {
        }
        
        public GetAllGuitarsResponse(TP_Guitar_Client.WS_GUITAR_Client.GetAllGuitarsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllGuitarsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TP_Guitar_Client.WS_GUITAR_Client.C_GUITAR[] GetAllGuitarsResult;
        
        public GetAllGuitarsResponseBody() {
        }
        
        public GetAllGuitarsResponseBody(TP_Guitar_Client.WS_GUITAR_Client.C_GUITAR[] GetAllGuitarsResult) {
            this.GetAllGuitarsResult = GetAllGuitarsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTypeBoisRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllTypeBois", Namespace="http://tempuri.org/", Order=0)]
        public TP_Guitar_Client.WS_GUITAR_Client.GetAllTypeBoisRequestBody Body;
        
        public GetAllTypeBoisRequest() {
        }
        
        public GetAllTypeBoisRequest(TP_Guitar_Client.WS_GUITAR_Client.GetAllTypeBoisRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllTypeBoisRequestBody {
        
        public GetAllTypeBoisRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTypeBoisResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllTypeBoisResponse", Namespace="http://tempuri.org/", Order=0)]
        public TP_Guitar_Client.WS_GUITAR_Client.GetAllTypeBoisResponseBody Body;
        
        public GetAllTypeBoisResponse() {
        }
        
        public GetAllTypeBoisResponse(TP_Guitar_Client.WS_GUITAR_Client.GetAllTypeBoisResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllTypeBoisResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TP_Guitar_Client.WS_GUITAR_Client.C_TYPEBOIS[] GetAllTypeBoisResult;
        
        public GetAllTypeBoisResponseBody() {
        }
        
        public GetAllTypeBoisResponseBody(TP_Guitar_Client.WS_GUITAR_Client.C_TYPEBOIS[] GetAllTypeBoisResult) {
            this.GetAllTypeBoisResult = GetAllTypeBoisResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTypesMicroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllTypesMicro", Namespace="http://tempuri.org/", Order=0)]
        public TP_Guitar_Client.WS_GUITAR_Client.GetAllTypesMicroRequestBody Body;
        
        public GetAllTypesMicroRequest() {
        }
        
        public GetAllTypesMicroRequest(TP_Guitar_Client.WS_GUITAR_Client.GetAllTypesMicroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllTypesMicroRequestBody {
        
        public GetAllTypesMicroRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTypesMicroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllTypesMicroResponse", Namespace="http://tempuri.org/", Order=0)]
        public TP_Guitar_Client.WS_GUITAR_Client.GetAllTypesMicroResponseBody Body;
        
        public GetAllTypesMicroResponse() {
        }
        
        public GetAllTypesMicroResponse(TP_Guitar_Client.WS_GUITAR_Client.GetAllTypesMicroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllTypesMicroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TP_Guitar_Client.WS_GUITAR_Client.C_MICRO[] GetAllTypesMicroResult;
        
        public GetAllTypesMicroResponseBody() {
        }
        
        public GetAllTypesMicroResponseBody(TP_Guitar_Client.WS_GUITAR_Client.C_MICRO[] GetAllTypesMicroResult) {
            this.GetAllTypesMicroResult = GetAllTypesMicroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTypesVibratoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllTypesVibrato", Namespace="http://tempuri.org/", Order=0)]
        public TP_Guitar_Client.WS_GUITAR_Client.GetAllTypesVibratoRequestBody Body;
        
        public GetAllTypesVibratoRequest() {
        }
        
        public GetAllTypesVibratoRequest(TP_Guitar_Client.WS_GUITAR_Client.GetAllTypesVibratoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllTypesVibratoRequestBody {
        
        public GetAllTypesVibratoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTypesVibratoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllTypesVibratoResponse", Namespace="http://tempuri.org/", Order=0)]
        public TP_Guitar_Client.WS_GUITAR_Client.GetAllTypesVibratoResponseBody Body;
        
        public GetAllTypesVibratoResponse() {
        }
        
        public GetAllTypesVibratoResponse(TP_Guitar_Client.WS_GUITAR_Client.GetAllTypesVibratoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllTypesVibratoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TP_Guitar_Client.WS_GUITAR_Client.C_VIBRATO[] GetAllTypesVibratoResult;
        
        public GetAllTypesVibratoResponseBody() {
        }
        
        public GetAllTypesVibratoResponseBody(TP_Guitar_Client.WS_GUITAR_Client.C_VIBRATO[] GetAllTypesVibratoResult) {
            this.GetAllTypesVibratoResult = GetAllTypesVibratoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCommandesExistantRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCommandesExistant", Namespace="http://tempuri.org/", Order=0)]
        public TP_Guitar_Client.WS_GUITAR_Client.GetAllCommandesExistantRequestBody Body;
        
        public GetAllCommandesExistantRequest() {
        }
        
        public GetAllCommandesExistantRequest(TP_Guitar_Client.WS_GUITAR_Client.GetAllCommandesExistantRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllCommandesExistantRequestBody {
        
        public GetAllCommandesExistantRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCommandesExistantResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCommandesExistantResponse", Namespace="http://tempuri.org/", Order=0)]
        public TP_Guitar_Client.WS_GUITAR_Client.GetAllCommandesExistantResponseBody Body;
        
        public GetAllCommandesExistantResponse() {
        }
        
        public GetAllCommandesExistantResponse(TP_Guitar_Client.WS_GUITAR_Client.GetAllCommandesExistantResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllCommandesExistantResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TP_Guitar_Client.WS_GUITAR_Client.C_COMMANDE[] GetAllCommandesExistantResult;
        
        public GetAllCommandesExistantResponseBody() {
        }
        
        public GetAllCommandesExistantResponseBody(TP_Guitar_Client.WS_GUITAR_Client.C_COMMANDE[] GetAllCommandesExistantResult) {
            this.GetAllCommandesExistantResult = GetAllCommandesExistantResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCommandesFaitesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCommandesFaites", Namespace="http://tempuri.org/", Order=0)]
        public TP_Guitar_Client.WS_GUITAR_Client.GetAllCommandesFaitesRequestBody Body;
        
        public GetAllCommandesFaitesRequest() {
        }
        
        public GetAllCommandesFaitesRequest(TP_Guitar_Client.WS_GUITAR_Client.GetAllCommandesFaitesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllCommandesFaitesRequestBody {
        
        public GetAllCommandesFaitesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCommandesFaitesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCommandesFaitesResponse", Namespace="http://tempuri.org/", Order=0)]
        public TP_Guitar_Client.WS_GUITAR_Client.GetAllCommandesFaitesResponseBody Body;
        
        public GetAllCommandesFaitesResponse() {
        }
        
        public GetAllCommandesFaitesResponse(TP_Guitar_Client.WS_GUITAR_Client.GetAllCommandesFaitesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllCommandesFaitesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TP_Guitar_Client.WS_GUITAR_Client.C_BON_COMMANDE[] GetAllCommandesFaitesResult;
        
        public GetAllCommandesFaitesResponseBody() {
        }
        
        public GetAllCommandesFaitesResponseBody(TP_Guitar_Client.WS_GUITAR_Client.C_BON_COMMANDE[] GetAllCommandesFaitesResult) {
            this.GetAllCommandesFaitesResult = GetAllCommandesFaitesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCommandeByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCommandeByID", Namespace="http://tempuri.org/", Order=0)]
        public TP_Guitar_Client.WS_GUITAR_Client.GetCommandeByIDRequestBody Body;
        
        public GetCommandeByIDRequest() {
        }
        
        public GetCommandeByIDRequest(TP_Guitar_Client.WS_GUITAR_Client.GetCommandeByIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCommandeByIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idCommande;
        
        public GetCommandeByIDRequestBody() {
        }
        
        public GetCommandeByIDRequestBody(int idCommande) {
            this.idCommande = idCommande;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCommandeByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCommandeByIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public TP_Guitar_Client.WS_GUITAR_Client.GetCommandeByIDResponseBody Body;
        
        public GetCommandeByIDResponse() {
        }
        
        public GetCommandeByIDResponse(TP_Guitar_Client.WS_GUITAR_Client.GetCommandeByIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCommandeByIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TP_Guitar_Client.WS_GUITAR_Client.C_BON_COMMANDE GetCommandeByIDResult;
        
        public GetCommandeByIDResponseBody() {
        }
        
        public GetCommandeByIDResponseBody(TP_Guitar_Client.WS_GUITAR_Client.C_BON_COMMANDE GetCommandeByIDResult) {
            this.GetCommandeByIDResult = GetCommandeByIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLastCommandeIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLastCommandeID", Namespace="http://tempuri.org/", Order=0)]
        public TP_Guitar_Client.WS_GUITAR_Client.GetLastCommandeIDRequestBody Body;
        
        public GetLastCommandeIDRequest() {
        }
        
        public GetLastCommandeIDRequest(TP_Guitar_Client.WS_GUITAR_Client.GetLastCommandeIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetLastCommandeIDRequestBody {
        
        public GetLastCommandeIDRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLastCommandeIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLastCommandeIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public TP_Guitar_Client.WS_GUITAR_Client.GetLastCommandeIDResponseBody Body;
        
        public GetLastCommandeIDResponse() {
        }
        
        public GetLastCommandeIDResponse(TP_Guitar_Client.WS_GUITAR_Client.GetLastCommandeIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLastCommandeIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetLastCommandeIDResult;
        
        public GetLastCommandeIDResponseBody() {
        }
        
        public GetLastCommandeIDResponseBody(string GetLastCommandeIDResult) {
            this.GetLastCommandeIDResult = GetLastCommandeIDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_GUITARSoapChannel : TP_Guitar_Client.WS_GUITAR_Client.WS_GUITARSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_GUITARSoapClient : System.ServiceModel.ClientBase<TP_Guitar_Client.WS_GUITAR_Client.WS_GUITARSoap>, TP_Guitar_Client.WS_GUITAR_Client.WS_GUITARSoap {
        
        public WS_GUITARSoapClient() {
        }
        
        public WS_GUITARSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_GUITARSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_GUITARSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_GUITARSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TP_Guitar_Client.WS_GUITAR_Client.NouvelleCommandeResponse TP_Guitar_Client.WS_GUITAR_Client.WS_GUITARSoap.NouvelleCommande(TP_Guitar_Client.WS_GUITAR_Client.NouvelleCommandeRequest request) {
            return base.Channel.NouvelleCommande(request);
        }
        
        public string NouvelleCommande(string NomClient, string DateCommande, string Montant, string TelephoneClient) {
            TP_Guitar_Client.WS_GUITAR_Client.NouvelleCommandeRequest inValue = new TP_Guitar_Client.WS_GUITAR_Client.NouvelleCommandeRequest();
            inValue.Body = new TP_Guitar_Client.WS_GUITAR_Client.NouvelleCommandeRequestBody();
            inValue.Body.NomClient = NomClient;
            inValue.Body.DateCommande = DateCommande;
            inValue.Body.Montant = Montant;
            inValue.Body.TelephoneClient = TelephoneClient;
            TP_Guitar_Client.WS_GUITAR_Client.NouvelleCommandeResponse retVal = ((TP_Guitar_Client.WS_GUITAR_Client.WS_GUITARSoap)(this)).NouvelleCommande(inValue);
            return retVal.Body.NouvelleCommandeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TP_Guitar_Client.WS_GUITAR_Client.NouvelleCommandeResponse> TP_Guitar_Client.WS_GUITAR_Client.WS_GUITARSoap.NouvelleCommandeAsync(TP_Guitar_Client.WS_GUITAR_Client.NouvelleCommandeRequest request) {
            return base.Channel.NouvelleCommandeAsync(request);
        }
        
        public System.Threading.Tasks.Task<TP_Guitar_Client.WS_GUITAR_Client.NouvelleCommandeResponse> NouvelleCommandeAsync(string NomClient, string DateCommande, string Montant, string TelephoneClient) {
            TP_Guitar_Client.WS_GUITAR_Client.NouvelleCommandeRequest inValue = new TP_Guitar_Client.WS_GUITAR_Client.NouvelleCommandeRequest();
            inValue.Body = new TP_Guitar_Client.WS_GUITAR_Client.NouvelleCommandeRequestBody();
            inValue.Body.NomClient = NomClient;
            inValue.Body.DateCommande = DateCommande;
            inValue.Body.Montant = Montant;
            inValue.Body.TelephoneClient = TelephoneClient;
            return ((TP_Guitar_Client.WS_GUITAR_Client.WS_GUITARSoap)(this)).NouvelleCommandeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TP_Guitar_Client.WS_GUITAR_Client.CommandeGuitarResponse TP_Guitar_Client.WS_GUITAR_Client.WS_GUITARSoap.CommandeGuitar(TP_Guitar_Client.WS_GUITAR_Client.CommandeGuitarRequest request) {
            return base.Channel.CommandeGuitar(request);
        }
        
        public void CommandeGuitar(string Nomguitar, string Micro1, string Micro2, string Micro3, string BoisManche, string BoisTouche, string BoisCorps, string NomVibrato, int idCommande) {
            TP_Guitar_Client.WS_GUITAR_Client.CommandeGuitarRequest inValue = new TP_Guitar_Client.WS_GUITAR_Client.CommandeGuitarRequest();
            inValue.Body = new TP_Guitar_Client.WS_GUITAR_Client.CommandeGuitarRequestBody();
            inValue.Body.Nomguitar = Nomguitar;
            inValue.Body.Micro1 = Micro1;
            inValue.Body.Micro2 = Micro2;
            inValue.Body.Micro3 = Micro3;
            inValue.Body.BoisManche = BoisManche;
            inValue.Body.BoisTouche = BoisTouche;
            inValue.Body.BoisCorps = BoisCorps;
            inValue.Body.NomVibrato = NomVibrato;
            inValue.Body.idCommande = idCommande;
            TP_Guitar_Client.WS_GUITAR_Client.CommandeGuitarResponse retVal = ((TP_Guitar_Client.WS_GUITAR_Client.WS_GUITARSoap)(this)).CommandeGuitar(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TP_Guitar_Client.WS_GUITAR_Client.CommandeGuitarResponse> TP_Guitar_Client.WS_GUITAR_Client.WS_GUITARSoap.CommandeGuitarAsync(TP_Guitar_Client.WS_GUITAR_Client.CommandeGuitarRequest request) {
            return base.Channel.CommandeGuitarAsync(request);
        }
        
        public System.Threading.Tasks.Task<TP_Guitar_Client.WS_GUITAR_Client.CommandeGuitarResponse> CommandeGuitarAsync(string Nomguitar, string Micro1, string Micro2, string Micro3, string BoisManche, string BoisTouche, string BoisCorps, string NomVibrato, int idCommande) {
            TP_Guitar_Client.WS_GUITAR_Client.CommandeGuitarRequest inValue = new TP_Guitar_Client.WS_GUITAR_Client.CommandeGuitarRequest();
            inValue.Body = new TP_Guitar_Client.WS_GUITAR_Client.CommandeGuitarRequestBody();
            inValue.Body.Nomguitar = Nomguitar;
            inValue.Body.Micro1 = Micro1;
            inValue.Body.Micro2 = Micro2;
            inValue.Body.Micro3 = Micro3;
            inValue.Body.BoisManche = BoisManche;
            inValue.Body.BoisTouche = BoisTouche;
            inValue.Body.BoisCorps = BoisCorps;
            inValue.Body.NomVibrato = NomVibrato;
            inValue.Body.idCommande = idCommande;
            return ((TP_Guitar_Client.WS_GUITAR_Client.WS_GUITARSoap)(this)).CommandeGuitarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TP_Guitar_Client.WS_GUITAR_Client.GetAllGuitarsResponse TP_Guitar_Client.WS_GUITAR_Client.WS_GUITARSoap.GetAllGuitars(TP_Guitar_Client.WS_GUITAR_Client.GetAllGuitarsRequest request) {
            return base.Channel.GetAllGuitars(request);
        }
        
        public TP_Guitar_Client.WS_GUITAR_Client.C_GUITAR[] GetAllGuitars() {
            TP_Guitar_Client.WS_GUITAR_Client.GetAllGuitarsRequest inValue = new TP_Guitar_Client.WS_GUITAR_Client.GetAllGuitarsRequest();
            inValue.Body = new TP_Guitar_Client.WS_GUITAR_Client.GetAllGuitarsRequestBody();
            TP_Guitar_Client.WS_GUITAR_Client.GetAllGuitarsResponse retVal = ((TP_Guitar_Client.WS_GUITAR_Client.WS_GUITARSoap)(this)).GetAllGuitars(inValue);
            return retVal.Body.GetAllGuitarsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TP_Guitar_Client.WS_GUITAR_Client.GetAllGuitarsResponse> TP_Guitar_Client.WS_GUITAR_Client.WS_GUITARSoap.GetAllGuitarsAsync(TP_Guitar_Client.WS_GUITAR_Client.GetAllGuitarsRequest request) {
            return base.Channel.GetAllGuitarsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TP_Guitar_Client.WS_GUITAR_Client.GetAllGuitarsResponse> GetAllGuitarsAsync() {
            TP_Guitar_Client.WS_GUITAR_Client.GetAllGuitarsRequest inValue = new TP_Guitar_Client.WS_GUITAR_Client.GetAllGuitarsRequest();
            inValue.Body = new TP_Guitar_Client.WS_GUITAR_Client.GetAllGuitarsRequestBody();
            return ((TP_Guitar_Client.WS_GUITAR_Client.WS_GUITARSoap)(this)).GetAllGuitarsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TP_Guitar_Client.WS_GUITAR_Client.GetAllTypeBoisResponse TP_Guitar_Client.WS_GUITAR_Client.WS_GUITARSoap.GetAllTypeBois(TP_Guitar_Client.WS_GUITAR_Client.GetAllTypeBoisRequest request) {
            return base.Channel.GetAllTypeBois(request);
        }
        
        public TP_Guitar_Client.WS_GUITAR_Client.C_TYPEBOIS[] GetAllTypeBois() {
            TP_Guitar_Client.WS_GUITAR_Client.GetAllTypeBoisRequest inValue = new TP_Guitar_Client.WS_GUITAR_Client.GetAllTypeBoisRequest();
            inValue.Body = new TP_Guitar_Client.WS_GUITAR_Client.GetAllTypeBoisRequestBody();
            TP_Guitar_Client.WS_GUITAR_Client.GetAllTypeBoisResponse retVal = ((TP_Guitar_Client.WS_GUITAR_Client.WS_GUITARSoap)(this)).GetAllTypeBois(inValue);
            return retVal.Body.GetAllTypeBoisResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TP_Guitar_Client.WS_GUITAR_Client.GetAllTypeBoisResponse> TP_Guitar_Client.WS_GUITAR_Client.WS_GUITARSoap.GetAllTypeBoisAsync(TP_Guitar_Client.WS_GUITAR_Client.GetAllTypeBoisRequest request) {
            return base.Channel.GetAllTypeBoisAsync(request);
        }
        
        public System.Threading.Tasks.Task<TP_Guitar_Client.WS_GUITAR_Client.GetAllTypeBoisResponse> GetAllTypeBoisAsync() {
            TP_Guitar_Client.WS_GUITAR_Client.GetAllTypeBoisRequest inValue = new TP_Guitar_Client.WS_GUITAR_Client.GetAllTypeBoisRequest();
            inValue.Body = new TP_Guitar_Client.WS_GUITAR_Client.GetAllTypeBoisRequestBody();
            return ((TP_Guitar_Client.WS_GUITAR_Client.WS_GUITARSoap)(this)).GetAllTypeBoisAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TP_Guitar_Client.WS_GUITAR_Client.GetAllTypesMicroResponse TP_Guitar_Client.WS_GUITAR_Client.WS_GUITARSoap.GetAllTypesMicro(TP_Guitar_Client.WS_GUITAR_Client.GetAllTypesMicroRequest request) {
            return base.Channel.GetAllTypesMicro(request);
        }
        
        public TP_Guitar_Client.WS_GUITAR_Client.C_MICRO[] GetAllTypesMicro() {
            TP_Guitar_Client.WS_GUITAR_Client.GetAllTypesMicroRequest inValue = new TP_Guitar_Client.WS_GUITAR_Client.GetAllTypesMicroRequest();
            inValue.Body = new TP_Guitar_Client.WS_GUITAR_Client.GetAllTypesMicroRequestBody();
            TP_Guitar_Client.WS_GUITAR_Client.GetAllTypesMicroResponse retVal = ((TP_Guitar_Client.WS_GUITAR_Client.WS_GUITARSoap)(this)).GetAllTypesMicro(inValue);
            return retVal.Body.GetAllTypesMicroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TP_Guitar_Client.WS_GUITAR_Client.GetAllTypesMicroResponse> TP_Guitar_Client.WS_GUITAR_Client.WS_GUITARSoap.GetAllTypesMicroAsync(TP_Guitar_Client.WS_GUITAR_Client.GetAllTypesMicroRequest request) {
            return base.Channel.GetAllTypesMicroAsync(request);
        }
        
        public System.Threading.Tasks.Task<TP_Guitar_Client.WS_GUITAR_Client.GetAllTypesMicroResponse> GetAllTypesMicroAsync() {
            TP_Guitar_Client.WS_GUITAR_Client.GetAllTypesMicroRequest inValue = new TP_Guitar_Client.WS_GUITAR_Client.GetAllTypesMicroRequest();
            inValue.Body = new TP_Guitar_Client.WS_GUITAR_Client.GetAllTypesMicroRequestBody();
            return ((TP_Guitar_Client.WS_GUITAR_Client.WS_GUITARSoap)(this)).GetAllTypesMicroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TP_Guitar_Client.WS_GUITAR_Client.GetAllTypesVibratoResponse TP_Guitar_Client.WS_GUITAR_Client.WS_GUITARSoap.GetAllTypesVibrato(TP_Guitar_Client.WS_GUITAR_Client.GetAllTypesVibratoRequest request) {
            return base.Channel.GetAllTypesVibrato(request);
        }
        
        public TP_Guitar_Client.WS_GUITAR_Client.C_VIBRATO[] GetAllTypesVibrato() {
            TP_Guitar_Client.WS_GUITAR_Client.GetAllTypesVibratoRequest inValue = new TP_Guitar_Client.WS_GUITAR_Client.GetAllTypesVibratoRequest();
            inValue.Body = new TP_Guitar_Client.WS_GUITAR_Client.GetAllTypesVibratoRequestBody();
            TP_Guitar_Client.WS_GUITAR_Client.GetAllTypesVibratoResponse retVal = ((TP_Guitar_Client.WS_GUITAR_Client.WS_GUITARSoap)(this)).GetAllTypesVibrato(inValue);
            return retVal.Body.GetAllTypesVibratoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TP_Guitar_Client.WS_GUITAR_Client.GetAllTypesVibratoResponse> TP_Guitar_Client.WS_GUITAR_Client.WS_GUITARSoap.GetAllTypesVibratoAsync(TP_Guitar_Client.WS_GUITAR_Client.GetAllTypesVibratoRequest request) {
            return base.Channel.GetAllTypesVibratoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TP_Guitar_Client.WS_GUITAR_Client.GetAllTypesVibratoResponse> GetAllTypesVibratoAsync() {
            TP_Guitar_Client.WS_GUITAR_Client.GetAllTypesVibratoRequest inValue = new TP_Guitar_Client.WS_GUITAR_Client.GetAllTypesVibratoRequest();
            inValue.Body = new TP_Guitar_Client.WS_GUITAR_Client.GetAllTypesVibratoRequestBody();
            return ((TP_Guitar_Client.WS_GUITAR_Client.WS_GUITARSoap)(this)).GetAllTypesVibratoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TP_Guitar_Client.WS_GUITAR_Client.GetAllCommandesExistantResponse TP_Guitar_Client.WS_GUITAR_Client.WS_GUITARSoap.GetAllCommandesExistant(TP_Guitar_Client.WS_GUITAR_Client.GetAllCommandesExistantRequest request) {
            return base.Channel.GetAllCommandesExistant(request);
        }
        
        public TP_Guitar_Client.WS_GUITAR_Client.C_COMMANDE[] GetAllCommandesExistant() {
            TP_Guitar_Client.WS_GUITAR_Client.GetAllCommandesExistantRequest inValue = new TP_Guitar_Client.WS_GUITAR_Client.GetAllCommandesExistantRequest();
            inValue.Body = new TP_Guitar_Client.WS_GUITAR_Client.GetAllCommandesExistantRequestBody();
            TP_Guitar_Client.WS_GUITAR_Client.GetAllCommandesExistantResponse retVal = ((TP_Guitar_Client.WS_GUITAR_Client.WS_GUITARSoap)(this)).GetAllCommandesExistant(inValue);
            return retVal.Body.GetAllCommandesExistantResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TP_Guitar_Client.WS_GUITAR_Client.GetAllCommandesExistantResponse> TP_Guitar_Client.WS_GUITAR_Client.WS_GUITARSoap.GetAllCommandesExistantAsync(TP_Guitar_Client.WS_GUITAR_Client.GetAllCommandesExistantRequest request) {
            return base.Channel.GetAllCommandesExistantAsync(request);
        }
        
        public System.Threading.Tasks.Task<TP_Guitar_Client.WS_GUITAR_Client.GetAllCommandesExistantResponse> GetAllCommandesExistantAsync() {
            TP_Guitar_Client.WS_GUITAR_Client.GetAllCommandesExistantRequest inValue = new TP_Guitar_Client.WS_GUITAR_Client.GetAllCommandesExistantRequest();
            inValue.Body = new TP_Guitar_Client.WS_GUITAR_Client.GetAllCommandesExistantRequestBody();
            return ((TP_Guitar_Client.WS_GUITAR_Client.WS_GUITARSoap)(this)).GetAllCommandesExistantAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TP_Guitar_Client.WS_GUITAR_Client.GetAllCommandesFaitesResponse TP_Guitar_Client.WS_GUITAR_Client.WS_GUITARSoap.GetAllCommandesFaites(TP_Guitar_Client.WS_GUITAR_Client.GetAllCommandesFaitesRequest request) {
            return base.Channel.GetAllCommandesFaites(request);
        }
        
        public TP_Guitar_Client.WS_GUITAR_Client.C_BON_COMMANDE[] GetAllCommandesFaites() {
            TP_Guitar_Client.WS_GUITAR_Client.GetAllCommandesFaitesRequest inValue = new TP_Guitar_Client.WS_GUITAR_Client.GetAllCommandesFaitesRequest();
            inValue.Body = new TP_Guitar_Client.WS_GUITAR_Client.GetAllCommandesFaitesRequestBody();
            TP_Guitar_Client.WS_GUITAR_Client.GetAllCommandesFaitesResponse retVal = ((TP_Guitar_Client.WS_GUITAR_Client.WS_GUITARSoap)(this)).GetAllCommandesFaites(inValue);
            return retVal.Body.GetAllCommandesFaitesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TP_Guitar_Client.WS_GUITAR_Client.GetAllCommandesFaitesResponse> TP_Guitar_Client.WS_GUITAR_Client.WS_GUITARSoap.GetAllCommandesFaitesAsync(TP_Guitar_Client.WS_GUITAR_Client.GetAllCommandesFaitesRequest request) {
            return base.Channel.GetAllCommandesFaitesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TP_Guitar_Client.WS_GUITAR_Client.GetAllCommandesFaitesResponse> GetAllCommandesFaitesAsync() {
            TP_Guitar_Client.WS_GUITAR_Client.GetAllCommandesFaitesRequest inValue = new TP_Guitar_Client.WS_GUITAR_Client.GetAllCommandesFaitesRequest();
            inValue.Body = new TP_Guitar_Client.WS_GUITAR_Client.GetAllCommandesFaitesRequestBody();
            return ((TP_Guitar_Client.WS_GUITAR_Client.WS_GUITARSoap)(this)).GetAllCommandesFaitesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TP_Guitar_Client.WS_GUITAR_Client.GetCommandeByIDResponse TP_Guitar_Client.WS_GUITAR_Client.WS_GUITARSoap.GetCommandeByID(TP_Guitar_Client.WS_GUITAR_Client.GetCommandeByIDRequest request) {
            return base.Channel.GetCommandeByID(request);
        }
        
        public TP_Guitar_Client.WS_GUITAR_Client.C_BON_COMMANDE GetCommandeByID(int idCommande) {
            TP_Guitar_Client.WS_GUITAR_Client.GetCommandeByIDRequest inValue = new TP_Guitar_Client.WS_GUITAR_Client.GetCommandeByIDRequest();
            inValue.Body = new TP_Guitar_Client.WS_GUITAR_Client.GetCommandeByIDRequestBody();
            inValue.Body.idCommande = idCommande;
            TP_Guitar_Client.WS_GUITAR_Client.GetCommandeByIDResponse retVal = ((TP_Guitar_Client.WS_GUITAR_Client.WS_GUITARSoap)(this)).GetCommandeByID(inValue);
            return retVal.Body.GetCommandeByIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TP_Guitar_Client.WS_GUITAR_Client.GetCommandeByIDResponse> TP_Guitar_Client.WS_GUITAR_Client.WS_GUITARSoap.GetCommandeByIDAsync(TP_Guitar_Client.WS_GUITAR_Client.GetCommandeByIDRequest request) {
            return base.Channel.GetCommandeByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<TP_Guitar_Client.WS_GUITAR_Client.GetCommandeByIDResponse> GetCommandeByIDAsync(int idCommande) {
            TP_Guitar_Client.WS_GUITAR_Client.GetCommandeByIDRequest inValue = new TP_Guitar_Client.WS_GUITAR_Client.GetCommandeByIDRequest();
            inValue.Body = new TP_Guitar_Client.WS_GUITAR_Client.GetCommandeByIDRequestBody();
            inValue.Body.idCommande = idCommande;
            return ((TP_Guitar_Client.WS_GUITAR_Client.WS_GUITARSoap)(this)).GetCommandeByIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TP_Guitar_Client.WS_GUITAR_Client.GetLastCommandeIDResponse TP_Guitar_Client.WS_GUITAR_Client.WS_GUITARSoap.GetLastCommandeID(TP_Guitar_Client.WS_GUITAR_Client.GetLastCommandeIDRequest request) {
            return base.Channel.GetLastCommandeID(request);
        }
        
        public string GetLastCommandeID() {
            TP_Guitar_Client.WS_GUITAR_Client.GetLastCommandeIDRequest inValue = new TP_Guitar_Client.WS_GUITAR_Client.GetLastCommandeIDRequest();
            inValue.Body = new TP_Guitar_Client.WS_GUITAR_Client.GetLastCommandeIDRequestBody();
            TP_Guitar_Client.WS_GUITAR_Client.GetLastCommandeIDResponse retVal = ((TP_Guitar_Client.WS_GUITAR_Client.WS_GUITARSoap)(this)).GetLastCommandeID(inValue);
            return retVal.Body.GetLastCommandeIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TP_Guitar_Client.WS_GUITAR_Client.GetLastCommandeIDResponse> TP_Guitar_Client.WS_GUITAR_Client.WS_GUITARSoap.GetLastCommandeIDAsync(TP_Guitar_Client.WS_GUITAR_Client.GetLastCommandeIDRequest request) {
            return base.Channel.GetLastCommandeIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<TP_Guitar_Client.WS_GUITAR_Client.GetLastCommandeIDResponse> GetLastCommandeIDAsync() {
            TP_Guitar_Client.WS_GUITAR_Client.GetLastCommandeIDRequest inValue = new TP_Guitar_Client.WS_GUITAR_Client.GetLastCommandeIDRequest();
            inValue.Body = new TP_Guitar_Client.WS_GUITAR_Client.GetLastCommandeIDRequestBody();
            return ((TP_Guitar_Client.WS_GUITAR_Client.WS_GUITARSoap)(this)).GetLastCommandeIDAsync(inValue);
        }
    }
}
